default:
	@echo	"list: recursively lists all the files above a particular size."
	@echo	"small: compresses all the listed files."
	@echo 	"restore: restoring all the compressed files to their original size."
list:
	@./size.sh
small:
	@./compress.sh
restore:
	@./restore.sh

